#!/usr/bin/env bash
# Bash script that pings an IP address passed as an arg
# Accepts a string as an arg
# Displays usage
# Ping the IP 5 times

# Check if an argument is provided
if [ $# -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
elif [ $# -gt 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
else

# Ping the IP address 5 times
	ping -c 5 $1
