#!/usr/bin/env bash
# Bash script that configures an Ubuntu server

cp /etc/hosts ~/hosts.new
echo -e "\n127.0.0.2\tlocalhost" >> ~/hosts.new
echo -e "\n8.8.8.8\tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
